package openapi

import "net/http"

func (generator *Generator) registerProblemSchema() {
	components := generator.document.
		Components.
		Schemas

	if _, exists := components["Problem"]; exists {
		return
	}

	components["ValidationSource"] = Schema{
		Type: "object",

		Required: []string{
			"in",
			"field",
		},

		Properties: map[string]*Schema{
			"in": {
				Type:        "string",
				Description: "Request location where the validation error occurred.",
				Enum: []any{
					"body",
					"path",
					"query",
					"header",
				},
				Example: "body",
			},
			"field": {
				Type:        "string",
				Description: "Field name or JSON pointer identifying the invalid value.",
			},
		},

		Example: map[string]any{
			"in":    "body",
			"field": "/name",
		},
	}

	components["ValidationError"] = Schema{
		Type: "object",

		Required: []string{
			"detail",
			"code",
			"source",
		},

		Properties: map[string]*Schema{
			"detail": {
				Type:        "string",
				Description: "Human-readable description of the validation error.",
			},
			"code": {
				Type:        "string",
				Description: "Machine-readable validation error code.",
			},
			"source": {
				Ref: schemaRef(
					"ValidationSource",
				),
			},
			"meta": {
				Type:                 "object",
				Description:          "Additional validation metadata.",
				AdditionalProperties: &Schema{},
			},
		},

		Example: map[string]any{
			"detail": "field is required",
			"code":   "required",
			"source": map[string]any{
				"in":    "body",
				"field": "/name",
			},
		},
	}

	components["Problem"] = Schema{
		Type:        "object",
		Description: "RFC 9457 problem details object.",
		Required: []string{
			"title",
			"status",
			"detail",
		},

		Properties: map[string]*Schema{
			"type": {
				Type:        "string",
				Description: "URI reference identifying the problem type.",
			},
			"title": {
				Type:        "string",
				Description: "Short, human-readable summary of the problem.",
			},
			"status": {
				Type:        "integer",
				Format:      "int32",
				Description: "HTTP status code generated by the origin server.",
			},
			"detail": {
				Type:        "string",
				Description: "Human-readable explanation specific to this occurrence.",
			},
			"instance": {
				Type:        "string",
				Description: "URI reference identifying the specific occurrence.",
			},
			"errors": {
				Type:        "array",
				Description: "Validation errors associated with the request.",

				Items: &Schema{
					Ref: schemaRef(
						"ValidationError",
					),
				},
			},
		},

		Example: map[string]any{
			"title":  "Validation failed",
			"status": http.StatusBadRequest,
			"detail": "Request validation failed",
			"errors": []any{
				map[string]any{
					"detail": "field is required",
					"code":   "required",
					"source": map[string]any{
						"in":    "body",
						"field": "/name",
					},
				},
			},
		},
	}
}
