package problem

import (
	"bytes"
	"encoding/json"
	"fmt"
	"maps"
	"net/http"
	"reflect"
	"slices"
	"strings"
)

// Problem represents an RFC 9457 problem details object.
//
//nolint:errname // the error type name `Problem` should conform to the `XxxError` format
type Problem struct {
	// Internal wrapped error. Not serialized.
	Err error `json:"-"`

	// A URI reference identifying the problem type.
	Type string `json:"type,omitempty"`

	// Short, human-readable summary of the problem.
	Title string `json:"title,omitempty"`

	// HTTP status code generated by the origin server.
	Status int `json:"status,omitempty"`

	// Human-readable explanation specific to this occurrence.
	Detail string `json:"detail,omitempty"`

	// URI reference identifying the specific occurrence.
	Instance string `json:"instance,omitempty"`

	// Validation errors associated with the request.
	Errors []ValidationError `json:"errors,omitempty"`

	// Extension members defined by RFC 9457.
	// These fields are serialized at the top level
	// of the problem response.
	extensions map[string]any
}

// New creates a Problem with the given status, title and detail.
func New(
	status int,
	title string,
	detail string,
) *Problem {
	return &Problem{
		Status: status,
		Title:  title,
		Detail: detail,
	}
}

// Error renders the problem as "status title: detail", so a Problem can be
// returned wherever an error is expected - a typed httpx.HandlerFunc, most
// commonly - and still read well in a log line. The response body sent to the
// client is the JSON from MarshalJSON, not this string.
// Error renders the problem as "status title: detail", so a Problem can be
// returned wherever an error is expected - a typed httpx.HandlerFunc, most
// commonly - and still read well in a log line. The response body sent to the
// client is the JSON from MarshalJSON, not this string.
func (problemInstance *Problem) Error() string {
	statusCode := problemInstance.StatusCode()

	title := problemInstance.Title
	if title == "" {
		title = http.StatusText(statusCode)
	}

	if problemInstance.Detail == "" {
		return fmt.Sprintf(
			"%d %s",
			statusCode,
			title,
		)
	}

	return fmt.Sprintf(
		"%d %s: %s",
		statusCode,
		title,
		problemInstance.Detail,
	)
}

// Unwrap returns the error passed to WithError, if any, so errors.Is and
// errors.As reach the underlying cause. That cause is never serialized: it
// stays available to the server's own logging while the client only ever sees
// the problem document.
func (problemInstance *Problem) Unwrap() error {
	return problemInstance.Err
}

// StatusCode returns the HTTP status code associated with the problem.
//
// If Status is not defined, http.StatusInternalServerError is returned.
func (problemInstance *Problem) StatusCode() int {
	if problemInstance.Status == 0 {
		return http.StatusInternalServerError
	}

	return problemInstance.Status
}

// WithType returns a copy with Type set.
//
// Every WithX and AddX method on Problem copies rather than mutating, which is
// what makes a package-level Problem safe to share:
//
//	var errNoSuchUser = problem.NewNotFound("no such user")
//
//	// Each request derives its own; the shared value is never touched.
//	return errNoSuchUser.WithInstance(request.URL.Path)
//
// Mutating in place would make that a data race between concurrent requests,
// and the sort that shows up as a wrong instance in someone else's response
// rather than as a crash.
func (problemInstance *Problem) WithType(value string) *Problem {
	copied := problemInstance.clone()
	copied.Type = value

	return copied
}

// WithInstance returns a copy with Instance set. httpx.WriteProblem fills
// Instance from the request path when it is still empty at write time, so an
// explicit WithInstance always wins over that default.
func (problemInstance *Problem) WithInstance(value string) *Problem {
	copied := problemInstance.clone()
	copied.Instance = value

	return copied
}

// WithError returns a copy carrying err as the internal cause, reachable with
// errors.Is and errors.As. Err is tagged `json:"-"`, so it never reaches the
// client whatever a ProblemMapper puts there.
func (problemInstance *Problem) WithError(err error) *Problem {
	copied := problemInstance.clone()
	copied.Err = err

	return copied
}

// AddError returns a copy with validationError appended to Errors.
//
// It returns the new value rather than modifying the receiver, so the result
// has to be used:
//
//	details = details.AddError(problem.NewBodyError(...))
func (problemInstance *Problem) AddError(validationError ValidationError) *Problem {
	copied := problemInstance.clone()
	copied.Errors = append(copied.Errors, validationError)

	return copied
}

// With attaches an RFC 9457 extension member to the problem, serialized
// at the top level of the JSON response alongside type/title/status/etc.
//
// It panics if key is empty or collides with one of the standard
// fields (type, title, status, detail, instance, errors): both are
// programming errors that should be caught during development rather
// than silently producing a malformed problem response.
func (problemInstance *Problem) With(key string, value any) *Problem {
	trimmedKey := strings.TrimSpace(key)

	if trimmedKey == "" {
		panic(ErrEmptyExtensionKey)
	}

	if isReservedField(trimmedKey) {
		panic(fmt.Errorf(
			"%w: %s",
			ErrReservedExtensionKey,
			trimmedKey,
		))
	}

	copied := problemInstance.clone()

	if copied.extensions == nil {
		copied.extensions = make(map[string]any)
	}

	copied.extensions[trimmedKey] = value

	return copied
}

// Extension returns the extension member stored under key, and whether it was
// present. Extension members are not exported as a field so that the standard
// RFC 9457 members cannot be shadowed by one; this is how you read them back.
func (problemInstance *Problem) Extension(key string) (any, bool) {
	value, found := problemInstance.extensions[strings.TrimSpace(key)]

	return value, found
}

// Extensions returns a copy of every extension member. Empty when there are
// none. Writing to the result does not affect the problem - use With for that.
func (problemInstance *Problem) Extensions() map[string]any {
	return maps.Clone(problemInstance.extensions)
}

// MarshalJSON renders the problem as RFC 9457 JSON, omitting any of
// the standard fields left at their zero value and interleaving
// extension members (added via With) at the top level of the object.
func (problemInstance *Problem) MarshalJSON() ([]byte, error) {
	type property struct {
		key   string
		value any
	}

	properties := []property{
		{
			key:   "type",
			value: problemInstance.Type,
		},
		{
			key:   "title",
			value: problemInstance.Title,
		},
		{
			key:   "status",
			value: problemInstance.Status,
		},
		{
			key:   "detail",
			value: problemInstance.Detail,
		},
		{
			key:   "instance",
			value: problemInstance.Instance,
		},
		{
			key:   "errors",
			value: problemInstance.Errors,
		},
	}

	buffer := bytes.NewBuffer(nil)

	buffer.WriteByte('{')

	isFirst := true

	for _, property := range properties {
		if isZeroValue(property.value) {
			continue
		}

		if !isFirst {
			buffer.WriteByte(',')
		}

		keyJSON, err := json.Marshal(
			property.key,
		)
		if err != nil {
			return nil, fmt.Errorf("marshal property value: %w", err)
		}

		valueJSON, err := json.Marshal(
			property.value,
		)
		if err != nil {
			return nil, fmt.Errorf("marshal property value: %w", err)
		}

		buffer.Write(keyJSON)

		buffer.WriteByte(':')

		buffer.Write(valueJSON)

		isFirst = false
	}

	// Sorted rather than ranged over directly: Go randomizes map iteration
	// order, so the same Problem would otherwise serialize to a different byte
	// sequence on each call. That breaks golden tests of error responses and
	// makes two identical requests return different bytes. RFC 9457 does not
	// order extension members, so any stable order will do; alphabetical is
	// the one a reader can predict.
	for _, key := range slices.Sorted(maps.Keys(problemInstance.extensions)) {
		value := problemInstance.extensions[key]

		if !isFirst {
			buffer.WriteByte(',')
		}

		keyJSON, err := json.Marshal(key)
		if err != nil {
			return nil, fmt.Errorf("marshal property key: %w", err)
		}

		valueJSON, err := json.Marshal(value)
		if err != nil {
			return nil, fmt.Errorf("marshal property value: %w", err)
		}

		buffer.Write(keyJSON)

		buffer.WriteByte(':')

		buffer.Write(valueJSON)

		isFirst = false
	}

	buffer.WriteByte('}')

	return buffer.Bytes(), nil
}

func isZeroValue(value any) bool {
	if value == nil {
		return true
	}

	return reflect.ValueOf(value).IsZero()
}

func isReservedField(field string) bool {
	switch field {
	case "type",
		"title",
		"status",
		"detail",
		"instance",
		"errors":
		return true
	default:
		return false
	}
}

// UnmarshalJSON parses an RFC 9457 problem document, routing every member the
// specification does not define into the extensions map so that a round trip
// preserves them.
//
// This is what a Go client consuming an arnon API uses. Without it, extension
// members - the whole point of the RFC's extensibility - would be dropped on
// decode, because they have no struct field to land in.
//
// Err is not populated: it is the server's own internal cause, never
// serialized, so there is nothing on the wire to restore.
func (problemInstance *Problem) UnmarshalJSON(data []byte) error {
	var members map[string]json.RawMessage

	err := json.Unmarshal(data, &members)
	if err != nil {
		return fmt.Errorf("unmarshal problem: %w", err)
	}

	*problemInstance = Problem{}

	for key, raw := range members {
		err = problemInstance.unmarshalMember(key, raw)
		if err != nil {
			return err
		}
	}

	return nil
}

// unmarshalMember assigns one top-level member, standard or extension.
func (problemInstance *Problem) unmarshalMember(
	key string,
	raw json.RawMessage,
) error {
	var target any

	switch key {
	case "type":
		target = &problemInstance.Type
	case "title":
		target = &problemInstance.Title
	case "status":
		target = &problemInstance.Status
	case "detail":
		target = &problemInstance.Detail
	case "instance":
		target = &problemInstance.Instance
	case "errors":
		target = &problemInstance.Errors

	default:
		var value any

		err := json.Unmarshal(raw, &value)
		if err != nil {
			return fmt.Errorf("unmarshal extension %q: %w", key, err)
		}

		if problemInstance.extensions == nil {
			problemInstance.extensions = make(map[string]any)
		}

		problemInstance.extensions[key] = value

		return nil
	}

	err := json.Unmarshal(raw, target)
	if err != nil {
		return fmt.Errorf("unmarshal %q: %w", key, err)
	}

	return nil
}

// clone returns an independent copy: the extensions map and the Errors slice
// are copied too, so a value derived from a shared Problem never writes
// through to it.
func (problemInstance *Problem) clone() *Problem {
	copied := *problemInstance

	if problemInstance.extensions != nil {
		copied.extensions = maps.Clone(problemInstance.extensions)
	}

	if problemInstance.Errors != nil {
		copied.Errors = slices.Clone(problemInstance.Errors)
	}

	return &copied
}
