package problem

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"reflect"
	"strings"
)

// Problem represents an RFC 9457 problem details object.
//
//nolint:errname // the error type name `Problem` should conform to the `XxxError` format
type Problem struct {
	// Internal wrapped error. Not serialized.
	Err error `json:"-"`

	// A URI reference identifying the problem type.
	Type string `json:"type,omitempty"`

	// Short, human-readable summary of the problem.
	Title string `json:"title,omitempty"`

	// HTTP status code generated by the origin server.
	Status int `json:"status,omitempty"`

	// Human-readable explanation specific to this occurrence.
	Detail string `json:"detail,omitempty"`

	// URI reference identifying the specific occurrence.
	Instance string `json:"instance,omitempty"`

	// Validation errors associated with the request.
	Errors []ValidationError `json:"errors,omitempty"`

	// Extension members defined by RFC 9457.
	// These fields are serialized at the top level
	// of the problem response.
	extensions map[string]any
}

// New creates a Problem with the given status, title and detail.
func New(
	status int,
	title string,
	detail string,
) *Problem {
	return &Problem{
		Status: status,
		Title:  title,
		Detail: detail,
	}
}

func (problemInstance *Problem) Error() string {
	statusCode := problemInstance.StatusCode()

	title := problemInstance.Title
	if title == "" {
		title = http.StatusText(statusCode)
	}

	if problemInstance.Detail == "" {
		return fmt.Sprintf(
			"%d %s",
			statusCode,
			title,
		)
	}

	return fmt.Sprintf(
		"%d %s: %s",
		statusCode,
		title,
		problemInstance.Detail,
	)
}

func (problemInstance *Problem) Unwrap() error {
	return problemInstance.Err
}

// StatusCode returns the HTTP status code associated with the problem.
//
// If Status is not defined, http.StatusInternalServerError is returned.
func (problemInstance *Problem) StatusCode() int {
	if problemInstance.Status == 0 {
		return http.StatusInternalServerError
	}

	return problemInstance.Status
}

// WithType sets Type and returns problemInstance for chaining -
// unlike openapi.Tag's WithX methods, this mutates in place (pointer
// receiver) rather than returning a copy.
func (problemInstance *Problem) WithType(value string) *Problem {
	problemInstance.Type = value

	return problemInstance
}

// WithInstance sets Instance and returns problemInstance for chaining
// (see WithType). httpx.WriteProblem auto-populates Instance from the
// request path when it's still empty at write time, so an explicit
// WithInstance call always wins over that default.
func (problemInstance *Problem) WithInstance(value string) *Problem {
	problemInstance.Instance = value

	return problemInstance
}

// WithError attaches an internal error for local logging/debugging -
// Err is tagged `json:"-"`, so it never reaches the client, regardless
// of what a ProblemMapper sets here.
func (problemInstance *Problem) WithError(err error) *Problem {
	problemInstance.Err = err

	return problemInstance
}

// AddError appends a field-level validation error to the problem's
// Errors slice.
func (problemInstance *Problem) AddError(validationError ValidationError) *Problem {
	problemInstance.Errors = append(
		problemInstance.Errors,
		validationError,
	)

	return problemInstance
}

// With attaches an RFC 9457 extension member to the problem, serialized
// at the top level of the JSON response alongside type/title/status/etc.
//
// It panics if key is empty or collides with one of the standard
// fields (type, title, status, detail, instance, errors): both are
// programming errors that should be caught during development rather
// than silently producing a malformed problem response.
func (problemInstance *Problem) With(key string, value any) *Problem {
	trimmedKey := strings.TrimSpace(key)

	if trimmedKey == "" {
		panic(ErrEmptyExtensionKey)
	}

	if isReservedField(trimmedKey) {
		panic(fmt.Errorf(
			"%w: %s",
			ErrReservedExtensionKey,
			trimmedKey,
		))
	}

	if problemInstance.extensions == nil {
		problemInstance.extensions = make(
			map[string]any,
		)
	}

	problemInstance.extensions[trimmedKey] = value

	return problemInstance
}

// MarshalJSON renders the problem as RFC 9457 JSON, omitting any of
// the standard fields left at their zero value and interleaving
// extension members (added via With) at the top level of the object.
func (problemInstance *Problem) MarshalJSON() ([]byte, error) {
	type property struct {
		key   string
		value any
	}

	properties := []property{
		{
			key:   "type",
			value: problemInstance.Type,
		},
		{
			key:   "title",
			value: problemInstance.Title,
		},
		{
			key:   "status",
			value: problemInstance.Status,
		},
		{
			key:   "detail",
			value: problemInstance.Detail,
		},
		{
			key:   "instance",
			value: problemInstance.Instance,
		},
		{
			key:   "errors",
			value: problemInstance.Errors,
		},
	}

	buffer := bytes.NewBuffer(nil)

	buffer.WriteByte('{')

	isFirst := true

	for _, property := range properties {
		if isZeroValue(property.value) {
			continue
		}

		if !isFirst {
			buffer.WriteByte(',')
		}

		keyJSON, err := json.Marshal(
			property.key,
		)
		if err != nil {
			return nil, fmt.Errorf("marshal property value: %w", err)
		}

		valueJSON, err := json.Marshal(
			property.value,
		)
		if err != nil {
			return nil, fmt.Errorf("marshal property value: %w", err)
		}

		buffer.Write(keyJSON)

		buffer.WriteByte(':')

		buffer.Write(valueJSON)

		isFirst = false
	}

	for key, value := range problemInstance.extensions {
		if !isFirst {
			buffer.WriteByte(',')
		}

		keyJSON, err := json.Marshal(key)
		if err != nil {
			return nil, fmt.Errorf("marshal property key: %w", err)
		}

		valueJSON, err := json.Marshal(value)
		if err != nil {
			return nil, fmt.Errorf("marshal property value: %w", err)
		}

		buffer.Write(keyJSON)

		buffer.WriteByte(':')

		buffer.Write(valueJSON)

		isFirst = false
	}

	buffer.WriteByte('}')

	return buffer.Bytes(), nil
}

func isZeroValue(value any) bool {
	if value == nil {
		return true
	}

	return reflect.ValueOf(value).IsZero()
}

func isReservedField(field string) bool {
	switch field {
	case "type",
		"title",
		"status",
		"detail",
		"instance",
		"errors":
		return true
	default:
		return false
	}
}
